### PR TITLE
david velasquez

### PR DESCRIPTION
**Pull request by davidxv15**

### CODE REVIEW

**Comment by BoognishSaves** [comment]
David, good job on this assignment. Please remember to read through the assignment to make sure you get everything. Missed adding your history to the solutions.txt. Also, commit frequently. You'll thank yourself as we work with more complex code.

**Comment by davidxv15** [comment]
Thank you. I know I did copy and paste the history into the solutions file, and left a comment in the correct format, but I’m not proficient in getting GitHub and vscode to “talk” to each other. So maybe I didn’t link them or a branch? 
I can paste the history and comment on slack or screen share during or after class today, because I’m sure course comments are meaningful data for instructors.

**Comment by BoognishSaves** [comment]
Don't stress it! It's very clear you did the work and comprehend the material. If you keep running in to the issue, we can take a look. Very happy to help!!!!!

**Comment by davidxv15** [comment]
Hey John Paul,
I was wondering if I could get more time on the control flow deliverable project. I recognized the functions and continued researching them, but I think I make a BIG mistake when trying to return to a previous commit.

**Pull request closed without merging**
